### ISSUE TITLE
客户机器（mac)上运行失败

### ISSUE THREAD

**Issue by luckypoem** [Yongke/shadowsocks-erlang#1]
hi.
服务器端运行正常：
root@ary:~/shadowsocks-erlang# lsof -i:8388
COMMAND    PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
beam.smp 21487 root    9u  IPv4 549614409      0t0  TCP *:8388 (LISTEN)
root@ary:~/shadowsocks-erlang#

root@ary:~/shadowsocks-erlang# ps aux|grep erl
root     21487  0.0 20.3 837208 26672 ?        Sl   Jun11   0:01 /root/erlang/otp_src_17.1/bin/x86_64-unknown-linux-gnu/beam.smp -- -root /root/erlang/otp_src_17.1 -progname erl -- -home /root -- -smp auto -config ./remote.config -pa ./ebin/ -boot start_sasl -s shadowsocks_app start -noshell -noinput
root     21571  0.0  0.6  11072   888 pts/3    S+   00:15   0:00 grep erl
root@ary:~/shadowsocks-erlang#

但是客户机器（mac)上运行失败：
yudeMacBook-Air:shadowsocks-erlang brite$ lsof -i:1080
yudeMacBook-Air:shadowsocks-erlang brite$ 
yudeMacBook-Air:shadowsocks-erlang brite$ erl -smp auto -config ./local.config -pa ./ebin/ -boot start_sasl -s shadowsocks_app start
Erlang/OTP 17 [erts-6.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

{"init terminating in do_boot",{undef,[{shadowsocks_app,start,[],[]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
yudeMacBook-Air:shadowsocks-erlang brite$

如何解决？

**Comment by Yongke** [comment]
./rebar compile 报错了吗？可以发出来看看吗?

**Comment by luckypoem** [comment]
hi.
我把shadowsocks-erlang目录删除，重新克隆，然后编译就ok了。
git clone https://github.com/Yongke/shadowsocks-erlang
cd shadowsocks-erlang
yudeMacBook-Air:shadowsocks-erlang brite$ ls
README.md include  log  remote.config
ebin  local.config rebar.conf src
yudeMacBook-Air:shadowsocks-erlang brite$ rebar compile
==> shadowsocks-erlang (compile)
Compiled src/shadowsocks_sup.erl
Compiled src/tcp_listener.erl
Compiled src/shadowsocks_fsm.erl
Compiled src/shadowsocks_app.erl
Compiled src/shadowsocks_crypt.erl
yudeMacBook-Air:shadowsocks-erlang brite$

然后运行：
erl -smp auto -config ./local.config -pa ./ebin/ -boot start_sasl -s shadowsocks_app start -detached
yudeMacBook-Air:shadowsocks-erlang brite$ lsof -i:1080
COMMAND    PID   USER   FD   TYPE            DEVICE SIZE/OFF NODE NAME
beam.smp 57691 brite   13u  IPv4 0x352e3a321ea1a93      0t0  TCP *:socks (LISTEN)
(beam.smp,即erl在监听1080端口，说明erl -smp auto -config ./local.config -pa ./ebin/ -boot start_sasl -s shadowsocks_app start -detached运行成功。
yudeMacBook-Air:shadowsocks-erlang brite$

然后设置浏览器的socks5代理为127.0.0.1:1080，即可翻墙。
